version: '1.0'

services:
  motoriep:
    build: .
    image: chc:0.5
    ports:
      - 3999:3000
    volumes:
      - /mnt/hdd/documents:/files
      - /home/rynakamura/docker-chc/converter:/converter
    tty: true
    command: sh -c "cd /converter && npm i && npm run prod"
    restart: unless-stopped